#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -l nodes=1:ppn=36:cascadelake
#PBS -A lp_ees_swm_ls_001
#PBS -m abe
#PBS -M michel.bechtold@kuleuven.be
#PBS -o CO_DA_log_000.txt
#PBS -e CO_DA_err_000.txt
#
###PBS -l pmem=10gb
###PBS -l partition=bigmem
#module load matlab/R2015b
#module load matlab/R2018a
source /data/leuven/317/vsc31786/miniconda/bin/activate py3

cd /data/leuven/317/vsc31786/python/bat_pyldas/batchscripts
#nohup process_ldas_output_default.py -r /scratch/leuven/317/vsc31786/output/TROPICS/ -e CONGO_M09_CLSM_v01 -d SMAP_EASEv2_M09 &> nohup_exp01.out &
#nohup process_ldas_output_default.py -r /scratch/leuven/317/vsc31786/output/TROPICS/ -e CONGO_M09_PEATCLSM_v01 -d SMAP_EASEv2_M09 &> nohup_exp02.out &
#nohup process_ldas_output_default.py -r /scratch/leuven/317/vsc31786/output/TROPICS/ -e CONGO_M09_PEATCLSMTN_v01 -d SMAP_EASEv2_M09 &> nohup_exp03a.out &
#nohup process_ldas_output_default.py -r /scratch/leuven/317/vsc31786/output/TROPICS/ -e CONGO_M09_PEATCLSMTD_v01 -d SMAP_EASEv2_M09 &> nohup_exp03b.out &
nohup projects/TROPICS_DA/process_ldas_output_default_TROPICS_DA.py -r /scratch/leuven/317/vsc31786/output/TROPICS/ -e CONGO_M09_CLSM_v01_SMOSfw_OL -d SMAP_EASEv2_M09 &> nohup_exp01.out &
nohup projects/TROPICS_DA/process_ldas_output_default_TROPICS_DA.py -r /scratch/leuven/317/vsc31786/output/TROPICS/ -e CONGO_M09_CLSM_v01_SMOSfw_DA -d SMAP_EASEv2_M09 &> nohup_exp02.out &
nohup projects/TROPICS_DA/process_ldas_output_default_TROPICS_DA.py -r /scratch/leuven/317/vsc31786/output/TROPICS/ -e CONGO_M09_PEATCLSMTN_v01_SMOSfw_OL -d SMAP_EASEv2_M09 &> nohup_exp03a.out &
nohup projects/TROPICS_DA/process_ldas_output_default_TROPICS_DA.py -r /scratch/leuven/317/vsc31786/output/TROPICS/ -e CONGO_M09_PEATCLSMTN_v01_SMOSfw_DA -d SMAP_EASEv2_M09 &> nohup_exp03b.out &
wait
